//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.5485
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckIEFeatureControl.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckIEFeatureControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   COMPRESSED_CONTENT_RESPECTS_SSL_CACHING_SETTING
        ///FEATURE_ACTIVEX_REPURPOSEDETECTION
        ///FEATURE_ADDON_MANAGEMENT
        ///FEATURE_ALLOW_EXPANDURI_BYPASS
        ///FEATURE_BEHAVIORS
        ///FEATURE_BLOCK_INPUT_PROMPTS
        ///FEATURE_BLOCK_LMZ_IMG
        ///FEATURE_BLOCK_LMZ_OBJECT
        ///FEATURE_BLOCK_LMZ_SCRIPT
        ///FEATURE_BLOCK_SETCAPTURE_XDOMAIN
        ///FEATURE_BUFFERBREAKING_818408
        ///FEATURE_CFSTR_INETURLW_DRAGDROP_FORMAT
        ///FEATURE_CLEANUP_AT_FLS
        ///FEATURE_CONSULT_MIME_KILLBIT_KB905915
        ///FEATURE_CONTENT_ADVISOR_FRAME_ABOUT_BLANK_SSL_KB827259
        ///FEATURE_CONVERT_A3A0IN [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Feat {
            get {
                return ResourceManager.GetString("Feat", resourceCulture);
            }
        }
    }
}
